server:
  port: 8001

## 配置dubbo
dubbo:
  application:
    name: dubbo-provider
  ## 配置注册中心
  registry:
    address: zookeeper://175.178.108.7:2181
    ## 设置连接超时时间 10s
    timeout: 10000
  ## 协议
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.tony.dubbo.provider.service
